# Chapter 3: It starts with a tensor

### Tensor initialization:

In [1]:
import torch
a = torch.ones(3)
a

tensor([1., 1., 1.])

In [2]:
a[1]

tensor(1.)

In [3]:
float(a[1])

1.0

In [4]:
a[2] = 2.0
a

tensor([1., 1., 2.])

In [5]:
# Initialize a tensor of zeros to get appropriate shape
points = torch.zeros(6)

# Set specific elements
points[0] = 4.0
points[1] = 1.0
points[2] = 5.0
points[3] = 3.0
points[4] = 2.0
points[5] = 1.0

In [6]:
points = torch.tensor([4.0, 1.0, 5.0, 3.0, 2.0, 1.0])
points

tensor([4., 1., 5., 3., 2., 1.])

In [7]:
float(points[0]), float(points[1])

(4.0, 1.0)

In [8]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [9]:
points.shape

torch.Size([3, 2])

In [29]:
points = torch.zeros(3, 2)
points

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [30]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [12]:
points[0, 1]

tensor(1.)

In [13]:
points[0]

tensor([4., 1.])

The output is another tensor that presents a different view of the same underlying
data. The new tensor is a 1D tensor of size 2, referencing the values of the first row in
the points tensor. Does this mean a new chunk of memory was allocated, values were
copied into it, and the new memory was returned wrapped in a new tensor object? No,
because that would be very inefficient, especially if we had millions of points.

### Indexing tensors

In [16]:
some_list = list(range(6))
some_list[:] # All elements

[0, 1, 2, 3, 4, 5]

In [17]:
some_list[1:4] # From 1 to 4, exclusive of 4.

[1, 2, 3]

In [18]:
some_list[1:] # From 1 to end

[1, 2, 3, 4, 5]

In [19]:
some_list[:4] # From start to 4, exclusive of 4.

[0, 1, 2, 3]

In [20]:
some_list[:-1] # From the start of the list to one before the last element

[0, 1, 2, 3, 4]

In [21]:
some_list[1:4:2] # Index 1 to 4, exclusive. Step by 2

[1, 3]

In [31]:
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [32]:
points[1:] # Implicit all columns

tensor([[5., 3.],
        [2., 1.]])

In [23]:
points[1:, :] # Explicit all columns

tensor([[5., 3.],
        [2., 1.]])

In [33]:
points[1:, 0] # All rows after the first; first (zero-index) column

tensor([5., 2.])

In [ ]:
points[None] # Adds a dimension of size 1; the same can be accomplished with points.unsqueeze(dim=0)

In addition to using ranges, PyTorch features a powerful form of indexing, called
advanced indexing, which we will look at in the next chapter.

### Broadcasting:

In [44]:
elements = torch.tensor([[0.,1.],[2.,3.]])
elements.shape

torch.Size([2, 2])

In [37]:
# here is an example of broadcasting with numpy
import numpy as np
np.broadcast_to(2, elements.shape)

array([[2, 2],
       [2, 2]])

We can see that broadcasting a scalar value to the shape of our tensor effectively copies the scalar value into a new tensor of identical dimension. This is what happens behind the scenes when we perform element-wise operations on tensors (arithmetic operations / comparison operations).

In [45]:
result = elements + 1
result

tensor([[1., 2.],
        [3., 4.]])

In [46]:
result = result + 1
result

tensor([[2., 3.],
        [4., 5.]])

In [47]:
result = result * 2
result

tensor([[ 4.,  6.],
        [ 8., 10.]])

In [48]:
result = result / 2
result

tensor([[2., 3.],
        [4., 5.]])

In [49]:
result > 4


tensor([[False, False],
        [False,  True]])

### Operations:

In [73]:
a = torch.ones(3, 2)
b = torch.ones(2, 3)
c = torch.ones(3, 2)

a = a + c
a

tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])

In [74]:
# Matrix multiplication
a @ b

tensor([[4., 4., 4.],
        [4., 4., 4.],
        [4., 4., 4.]])

In [75]:
a.matmul(b)

tensor([[4., 4., 4.],
        [4., 4., 4.],
        [4., 4., 4.]])

These are two identical ways to handle matrix multiplication.

To compute element-wise multiplication, we do:

In [76]:
a * c

tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])

Or:

In [77]:
a.mul(c)

tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])

As demonstrated before, automatic broadcasting enables us to perform element-wise multiplication when multiplying a matrix by a scalar:

In [78]:
a * 4

tensor([[8., 8.],
        [8., 8.],
        [8., 8.]])

### Tensor element types:

PyTorch supports 12 different dtype arguments:
- torch.float32 or torch.float—32-bit floating-point
- torch.float64 or torch.double—64-bit, double-precision floating-point
- torch.complex64 or torch.cfloat—64-bit complex
- torch.complex128 or torch.cdouble—128-bit complex
- torch.float16 or torch.half—16-bit, half-precision floating-point
- torch.bfloat16—brain float 16-bit, half-precision floating-point (This is a new
data type introduced by Google in 2019. It is similar to torch.float16 but uses a
different encoding that can encode a larger range, while float16 is better for
precision.)
- torch.int8—signed 8-bit integers
- torch.uint8—unsigned 8-bit integers
- torch.int16 or torch.short—signed 16-bit integers
- torch.int32 or torch.int—signed 32-bit integers
- torch.int64 or torch.long—signed 64-bit integers
- torch.bool—Boolean
The default data type for tensors is 32-bit floating-point.


In [50]:
double_points = torch.ones(10, 2, dtype=torch.double)
short_points = torch.tensor([[1, 2], [3, 4]], dtype=torch.short)

In [51]:
double_points

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]], dtype=torch.float64)

In [52]:
short_points

tensor([[1, 2],
        [3, 4]], dtype=torch.int16)

In [53]:
short_points.dtype

torch.int16

We can also cast the output of a tensor creation function to the right type using the
corresponding casting method, such as


In [54]:
double_points = torch.zeros(10, 2).double()
short_points = torch.ones(10, 2).short()

or the more convenient to method:

In [ ]:
double_points = torch.zeros(10, 2).to(torch.double)
short_points = torch.ones(10, 2).to(dtype=torch.short)

Under the hood, to checks whether the conversion is necessary and, if so, does it. The
dtype-named casting methods like float are shorthand for to, but the to method can
take additional arguments, which we’ll discuss later.

 When mixing input types in operations, the inputs are converted to the larger type
automatically

### The PyTorch API

In [55]:
a = torch.ones(3, 2)
a_t = torch.transpose(a, 0, 1) # Called from the torch module
a.shape, a_t.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [56]:
a = torch.ones(3, 2)
a_t = a.transpose(0, 1) # Called on the tensor itself
a.shape, a_t.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

There is no difference between these two approaches. Both are valid.

### Tensors to the GPU:

We can directly assign a tensor to the GPU:

In [ ]:
points_gpu = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]], device='cuda')

We could instead copy a tensor created on the CPU onto the GPU using the to method:

In [ ]:
points_gpu = points.to(device='cuda')

 If our machine has more than one GPU, we can also decide on which GPU we allocate the tensor by passing a zero-based integer identifying the GPU on the machine,
such as:

In [ ]:
points_gpu = points.to(device='cuda:0')

In [ ]:
# CPU computation
points = 2 * points

# GPU computation
points_gpu=2* points.to(device='cuda')

To move the tensor back to the CPU, we need to provide a cpu argument to the to method, such as:

In [ ]:
points_cpu = points_gpu.to(device='cpu')

###  NumPy interoperability

In [57]:
points = torch.ones(3, 4)
points_np = points.numpy()
points_np

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

Interestingly, the returned array shares the same underlying buffer
with the tensor storage. This means the numpy method can be effectively executed at
basically no cost, as long as the data sits in CPU RAM. It also means modifying the
NumPy array will lead to a change in the originating tensor. If the tensor is allocated
on the GPU, PyTorch will make a copy of the content of the tensor into a NumPy array
allocated on the CPU.

In [59]:
points = torch.from_numpy(points_np)
points

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

Which will use the same buffer-sharing strategy we just described.

NOTE:While the default numeric type in PyTorch is 32-bit floating-point, for
NumPy it is 64-bit. As discussed in section 3.5.2, we usually want to use 32-bit
floating-points, so we need to make sure we have tensors of dtype torch.float
after converting.

### Serialization:

PyTorch uses pickle to serialize the tensor object, plus dedicated serialization code
for the storage.

While we can quickly save tensors this way if we only want to load them with PyTorch,
the file format itself is not interoperable: we can’t read the tensor with software other
than PyTorch.

In [61]:
torch.save(points, '../data/archive/ourpoints.t')

In [62]:
new_points = torch.load('../data/archive/ourpoints.t')
new_points

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

HDF5 is a portable, widely supported format for representing serialized multidimensional arrays, organized in a
nested key-value dictionary. Python supports HDF5 through the h5py library (http://
www.h5py.org/), which accepts and returns data in the form of NumPy arrays.

In [63]:
import h5py
f = h5py.File('../data/archive/ourpoints.hdf5', 'w')
dset = f.create_dataset('my_points', data=points.numpy())
f.close()

In [64]:
f = h5py.File('../data/archive/ourpoints.hdf5', 'r')
dset = f['my_points']
last_points = dset[-2:]

The data is not loaded when the file is opened or the dataset is required. Rather, the
data stays on disk until we request the second and last rows in the dataset. Closing the HDFS file invalidates the
datasets, and trying to access dset afterward will give an exception.

Owing to this fact, we can pass the returned object to the torch.from_numpy function
to obtain a tensor directly. In this case, the data is copied over to the tensor’s storage:

In [65]:
last_points = torch.from_numpy(dset[-2:])
f.close()

In [66]:
last_points

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])