# Chapter 3: It starts with a tensor

### Tensor initialization:

In [1]:
import torch
a = torch.ones(3)
a

tensor([1., 1., 1.])

In [2]:
a[1]

tensor(1.)

In [3]:
float(a[1])

1.0

In [4]:
a[2] = 2.0
a

tensor([1., 1., 2.])

In [5]:
# Initialize a tensor of zeros to get appropriate shape
points = torch.zeros(6)

# Set specific elements
points[0] = 4.0
points[1] = 1.0
points[2] = 5.0
points[3] = 3.0
points[4] = 2.0
points[5] = 1.0

In [6]:
points = torch.tensor([4.0, 1.0, 5.0, 3.0, 2.0, 1.0])
points

tensor([4., 1., 5., 3., 2., 1.])

In [7]:
float(points[0]), float(points[1])

(4.0, 1.0)

In [8]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [9]:
points.shape

torch.Size([3, 2])

In [29]:
points = torch.zeros(3, 2)
points

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [30]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [12]:
points[0, 1]

tensor(1.)

In [13]:
points[0]

tensor([4., 1.])

The output is another tensor that presents a different view of the same underlying
data. The new tensor is a 1D tensor of size 2, referencing the values of the first row in
the points tensor. Does this mean a new chunk of memory was allocated, values were
copied into it, and the new memory was returned wrapped in a new tensor object? No,
because that would be very inefficient, especially if we had millions of points.

### Indexing tensors

In [16]:
some_list = list(range(6))
some_list[:]

[0, 1, 2, 3, 4, 5]

In [17]:
some_list[1:4]

[1, 2, 3]

In [18]:
some_list[1:]

[1, 2, 3, 4, 5]

In [19]:
some_list[:4]

[0, 1, 2, 3]

In [20]:
some_list[:-1] # From the start of the list to one before the last element

[0, 1, 2, 3, 4]

In [21]:
some_list[1:4:2] # Index 1 to 4, exclusive. Step by 2

[1, 3]

In [31]:
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [32]:
points[1:] # Implicit all columns

tensor([[5., 3.],
        [2., 1.]])

In [23]:
points[1:, :] # Explicit all columns

tensor([[5., 3.],
        [2., 1.]])

In [33]:
points[1:, 0] # All rows after the first; first (zero-index) column

tensor([5., 2.])

In [ ]:
points[None] # Adds a dimension of size 1; the same can be accomplished with points.unsqueeze(dim=0)

In addition to using ranges, PyTorch features a powerful form of indexing, called
advanced indexing, which we will look at in the next chapter.